# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.4 2001/12/04 04:56:02 keller Exp $
#
# (c) The GHC Team, 1999
#

TOP=../..
include $(TOP)/mk/boilerplate.mk

PACKAGE = xlib
IS_CBITS_LIB = YES
INSTALL_DATAS+=HsXlib.h

include $(TOP)/mk/target.mk
