# -----------------------------------------------------------------------------=
# $Id: Makefile,v 1.7 2002/02/12 15:17:27 simonmar Exp $
#
# (c) The GHC Team 1997-2000
#

TOP = ../../..
include $(TOP)/mk/boilerplate.mk

PACKAGE = HGL
PACKAGE_DEPS = xlib concurrent

SRC_HC_OPTS    += -fglasgow-exts
SRC_HC_OPTS    += $(X_CFLAGS)

include $(TOP)/mk/target.mk

