# -----------------------------------------------------------------------------=
# $Id: Makefile,v 1.20 2002/02/12 15:17:29 simonmar Exp $
#
# (c) The University of Glasgow 2002
#

TOP=..
include $(TOP)/mk/boilerplate.mk

PACKAGE  = lang
SUBDIRS  = cbits
ALL_DIRS = monads

SRC_HC_OPTS += -cpp -fglasgow-exts -Icbits

include $(TOP)/mk/target.mk
