# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.5.14.2 2003/11/20 10:03:45 simonmar Exp $

TOP=..
include $(TOP)/mk/boilerplate.mk

ALL_DIRS =
PACKAGE      = haskell98
PACKAGE_DEPS = base

SRC_HC_OPTS += -cpp
SRC_HADDOCK_OPTS += -t "Haskell Hierarchical Libraries ($(PACKAGE) package)"

include $(TOP)/mk/target.mk
