#include <windows.h>
#include "errors.h"
#include "win32debug.h"
#include "finalizers.h"
#include "HsFFI.h"
extern void* prim_hKEY_CLASSES_ROOT();
extern void* access_prim_hKEY_CLASSES_ROOT_gc_res3(HsPtr);
extern HKEY access_prim_hKEY_CLASSES_ROOT_gc_res1(HsPtr);
extern void* prim_hKEY_CURRENT_CONFIG();
extern void* access_prim_hKEY_CURRENT_CONFIG_gc_res3(HsPtr);
extern HKEY access_prim_hKEY_CURRENT_CONFIG_gc_res1(HsPtr);
extern void* prim_hKEY_CURRENT_USER();
extern void* access_prim_hKEY_CURRENT_USER_gc_res3(HsPtr);
extern HKEY access_prim_hKEY_CURRENT_USER_gc_res1(HsPtr);
extern void* prim_hKEY_LOCAL_MACHINE();
extern void* access_prim_hKEY_LOCAL_MACHINE_gc_res3(HsPtr);
extern HKEY access_prim_hKEY_LOCAL_MACHINE_gc_res1(HsPtr);
extern void* prim_hKEY_USERS();
extern void* access_prim_hKEY_USERS_gc_res3(HsPtr);
extern HKEY access_prim_hKEY_USERS_gc_res1(HsPtr);
extern void* prim_regCloseKey(HKEY arg1);
extern int access_prim_regCloseKey_gc_failed(HsPtr);
extern void* access_prim_regCloseKey_gc_failstring(HsPtr);
extern void* prim_regConnectRegistry(char * arg1,HKEY arg2);
extern void* access_prim_regConnectRegistry_gc_res3(HsPtr);
extern HKEY access_prim_regConnectRegistry_gc_res1(HsPtr);
extern int access_prim_regConnectRegistry_gc_failed(HsPtr);
extern void* access_prim_regConnectRegistry_gc_failstring(HsPtr);
extern void* prim_regCreateKey(HKEY arg1,char * arg2);
extern void* access_prim_regCreateKey_gc_res3(HsPtr);
extern HKEY access_prim_regCreateKey_gc_res1(HsPtr);
extern int access_prim_regCreateKey_gc_failed(HsPtr);
extern void* access_prim_regCreateKey_gc_failstring(HsPtr);
extern int prim_rEG_OPTION_NON_VOLATILE();
extern int prim_rEG_OPTION_VOLATILE();
extern int prim_kEY_ALL_ACCESS();
extern int prim_kEY_CREATE_LINK();
extern int prim_kEY_CREATE_SUB_KEY();
extern int prim_kEY_ENUMERATE_SUB_KEYS();
extern int prim_kEY_EXECUTE();
extern int prim_kEY_NOTIFY();
extern int prim_kEY_QUERY_VALUE();
extern int prim_kEY_READ();
extern int prim_kEY_SET_VALUE();
extern int prim_kEY_WRITE();
extern void* prim_regCreateKeyEx(HKEY arg1,char * arg2,char * arg3,int arg4,int arg5,void * arg6);
extern void* access_prim_regCreateKeyEx_gc_res3(HsPtr);
extern HKEY access_prim_regCreateKeyEx_gc_res1(HsPtr);
extern int access_prim_regCreateKeyEx_gc_res5(HsPtr);
extern int access_prim_regCreateKeyEx_gc_failed(HsPtr);
extern void* access_prim_regCreateKeyEx_gc_failstring(HsPtr);
extern void* prim_regDeleteKey(HKEY arg1,char * arg2);
extern int access_prim_regDeleteKey_gc_failed(HsPtr);
extern void* access_prim_regDeleteKey_gc_failstring(HsPtr);
extern void* prim_regDeleteValue(HKEY arg1,char * arg2);
extern int access_prim_regDeleteValue_gc_failed(HsPtr);
extern void* access_prim_regDeleteValue_gc_failstring(HsPtr);
extern DWORD prim_readWord32Addr(char* s,int i);
extern void* prim_regEnumKey(HKEY arg1,DWORD arg2,void * arg3,DWORD arg4);
extern char * access_prim_regEnumKey_gc_res2(HsPtr);
extern int access_prim_regEnumKey_gc_res3(HsPtr);
extern int access_prim_regEnumKey_gc_failed(HsPtr);
extern void* access_prim_regEnumKey_gc_failstring(HsPtr);
extern void* prim_regEnumValue(HKEY arg1,DWORD arg2,void * arg3,DWORD arg4,void * arg5,DWORD arg6);
extern int access_prim_regEnumValue_gc_res1(HsPtr);
extern char * access_prim_regEnumValue_gc_res3(HsPtr);
extern int access_prim_regEnumValue_gc_res4(HsPtr);
extern int access_prim_regEnumValue_gc_failed(HsPtr);
extern void* access_prim_regEnumValue_gc_failstring(HsPtr);
extern void* prim_regFlushKey(HKEY arg1);
extern int access_prim_regFlushKey_gc_failed(HsPtr);
extern void* access_prim_regFlushKey_gc_failstring(HsPtr);
extern void* prim_regLoadKey(HKEY arg1,char * arg2,char * arg3);
extern int access_prim_regLoadKey_gc_failed(HsPtr);
extern void* access_prim_regLoadKey_gc_failstring(HsPtr);
extern int prim_rEG_NOTIFY_CHANGE_NAME();
extern int prim_rEG_NOTIFY_CHANGE_ATTRIBUTES();
extern int prim_rEG_NOTIFY_CHANGE_LAST_SET();
extern int prim_rEG_NOTIFY_CHANGE_SECURITY();
extern void* prim_regNotifyChangeKeyValue(HKEY arg1,int arg2,int arg3,HANDLE arg4,int arg5);
extern int access_prim_regNotifyChangeKeyValue_gc_failed(HsPtr);
extern void* access_prim_regNotifyChangeKeyValue_gc_failstring(HsPtr);
extern void* prim_regOpenKey(HKEY arg1,char * arg2);
extern void* access_prim_regOpenKey_gc_res3(HsPtr);
extern HKEY access_prim_regOpenKey_gc_res1(HsPtr);
extern int access_prim_regOpenKey_gc_failed(HsPtr);
extern void* access_prim_regOpenKey_gc_failstring(HsPtr);
extern void* prim_regOpenKeyEx(HKEY arg1,char * arg2,int arg3);
extern void* access_prim_regOpenKeyEx_gc_res3(HsPtr);
extern HKEY access_prim_regOpenKeyEx_gc_res1(HsPtr);
extern int access_prim_regOpenKeyEx_gc_failed(HsPtr);
extern void* access_prim_regOpenKeyEx_gc_failstring(HsPtr);
extern void* prim_regQueryInfoKey(HKEY arg1);
extern char * access_prim_regQueryInfoKey_str(HsPtr);
extern int access_prim_regQueryInfoKey_cbClass(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cSubKeys(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cbMaxSubKeyLen(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cbMaxClassLen(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cValues(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cbMaxValueNameLen(HsPtr);
extern DWORD access_prim_regQueryInfoKey_cbMaxValueLen(HsPtr);
extern int access_prim_regQueryInfoKey_cbSecurityDescriptor(HsPtr);
extern DWORD access_prim_regQueryInfoKey_gc_res2(HsPtr);
extern DWORD access_prim_regQueryInfoKey_gc_res3(HsPtr);
extern int access_prim_regQueryInfoKey_gc_failed(HsPtr);
extern void* access_prim_regQueryInfoKey_gc_failstring(HsPtr);
extern void* prim_regQueryValueKey(HKEY arg1,char * arg2);
extern char * access_prim_regQueryValueKey_gc_res2(HsPtr);
extern int access_prim_regQueryValueKey_gc_failed(HsPtr);
extern void* access_prim_regQueryValueKey_gc_failstring(HsPtr);
extern void* prim_regQueryValue(HKEY arg1,char * arg2);
extern char * access_prim_regQueryValue_gc_res2(HsPtr);
extern int access_prim_regQueryValue_gc_failed(HsPtr);
extern void* access_prim_regQueryValue_gc_failstring(HsPtr);
extern void* prim_regQueryValueEx(HKEY arg1,char * arg2,void * arg3,int arg4);
extern int access_prim_regQueryValueEx_gc_res1(HsPtr);
extern int access_prim_regQueryValueEx_gc_failed(HsPtr);
extern void* access_prim_regQueryValueEx_gc_failstring(HsPtr);
extern void* prim_regReplaceKey(HKEY arg1,char * arg2,char * arg3,char * arg4);
extern int access_prim_regReplaceKey_gc_failed(HsPtr);
extern void* access_prim_regReplaceKey_gc_failstring(HsPtr);
extern int prim_rEG_WHOLE_HIVE_VOLATILE();
extern int prim_rEG_REFRESH_HIVE();
extern int prim_rEG_NO_LAZY_FLUSH();
extern void* prim_regRestoreKey(HKEY arg1,char * arg2,int arg3);
extern int access_prim_regRestoreKey_gc_failed(HsPtr);
extern void* access_prim_regRestoreKey_gc_failstring(HsPtr);
extern void* prim_regSaveKey(HKEY arg1,char * arg2,void * arg3);
extern int access_prim_regSaveKey_gc_failed(HsPtr);
extern void* access_prim_regSaveKey_gc_failstring(HsPtr);
extern void* prim_regSetValue(HKEY arg1,char * arg2,char * arg3,int arg4);
extern int access_prim_regSetValue_gc_failed(HsPtr);
extern void* access_prim_regSetValue_gc_failstring(HsPtr);
extern int prim_rEG_BINARY();
extern int prim_rEG_DWORD();
extern int prim_rEG_DWORD_LITTLE_ENDIAN();
extern int prim_rEG_DWORD_BIG_ENDIAN();
extern int prim_rEG_EXPAND_SZ();
extern int prim_rEG_LINK();
extern int prim_rEG_MULTI_SZ();
extern int prim_rEG_NONE();
extern int prim_rEG_RESOURCE_LIST();
extern int prim_rEG_SZ();
extern void* prim_regSetValueEx(HKEY arg1,char * arg2,int arg3,void * arg4,int arg5);
extern int access_prim_regSetValueEx_gc_failed(HsPtr);
extern void* access_prim_regSetValueEx_gc_failstring(HsPtr);
extern void* prim_regUnLoadKey(HKEY arg1,char * arg2);
extern int access_prim_regUnLoadKey_gc_failed(HsPtr);
extern void* access_prim_regUnLoadKey_gc_failstring(HsPtr);
