#include <windows.h>
#include "errors.h"
#include "win32debug.h"
#include "finalizers.h"
#include "HsFFI.h"
extern void* prim_setArcDirection(HDC arg1,WORD arg2);
extern WORD access_prim_setArcDirection_res1(HsPtr);
extern int access_prim_setArcDirection_gc_failed(HsPtr);
extern void* access_prim_setArcDirection_gc_failstring(HsPtr);
extern void* prim_getArcDirection(HDC arg1);
extern WORD access_prim_getArcDirection_res1(HsPtr);
extern int access_prim_getArcDirection_gc_failed(HsPtr);
extern void* access_prim_getArcDirection_gc_failstring(HsPtr);
extern void* prim_setPolyFillMode(HDC arg1,WORD arg2);
extern WORD access_prim_setPolyFillMode_res1(HsPtr);
extern int access_prim_setPolyFillMode_gc_failed(HsPtr);
extern void* access_prim_setPolyFillMode_gc_failstring(HsPtr);
extern void* prim_getPolyFillMode(HDC arg1);
extern WORD access_prim_getPolyFillMode_res1(HsPtr);
extern int access_prim_getPolyFillMode_gc_failed(HsPtr);
extern void* access_prim_getPolyFillMode_gc_failstring(HsPtr);
extern void* prim_setGraphicsMode(HDC arg1,DWORD arg2);
extern DWORD access_prim_setGraphicsMode_res1(HsPtr);
extern int access_prim_setGraphicsMode_gc_failed(HsPtr);
extern void* access_prim_setGraphicsMode_gc_failstring(HsPtr);
extern void* prim_getGraphicsMode(HDC arg1);
extern DWORD access_prim_getGraphicsMode_res1(HsPtr);
extern int access_prim_getGraphicsMode_gc_failed(HsPtr);
extern void* access_prim_getGraphicsMode_gc_failstring(HsPtr);
extern void* prim_setStretchBltMode(HDC arg1,UINT arg2);
extern UINT access_prim_setStretchBltMode_res1(HsPtr);
extern int access_prim_setStretchBltMode_gc_failed(HsPtr);
extern void* access_prim_setStretchBltMode_gc_failstring(HsPtr);
extern void* prim_getStretchBltMode(HDC arg1);
extern UINT access_prim_getStretchBltMode_res1(HsPtr);
extern int access_prim_getStretchBltMode_gc_failed(HsPtr);
extern void* access_prim_getStretchBltMode_gc_failstring(HsPtr);
extern void* prim_setBkColor(HDC arg1,DWORD arg2);
extern DWORD access_prim_setBkColor_res1(HsPtr);
extern int access_prim_setBkColor_gc_failed(HsPtr);
extern void* access_prim_setBkColor_gc_failstring(HsPtr);
extern void* prim_getBkColor(HDC arg1);
extern DWORD access_prim_getBkColor_res1(HsPtr);
extern int access_prim_getBkColor_gc_failed(HsPtr);
extern void* access_prim_getBkColor_gc_failstring(HsPtr);
extern void* prim_setTextColor(HDC arg1,DWORD arg2);
extern DWORD access_prim_setTextColor_res1(HsPtr);
extern int access_prim_setTextColor_gc_failed(HsPtr);
extern void* access_prim_setTextColor_gc_failstring(HsPtr);
extern void* prim_getTextColor(HDC arg1);
extern DWORD access_prim_getTextColor_res1(HsPtr);
extern int access_prim_getTextColor_gc_failed(HsPtr);
extern void* access_prim_getTextColor_gc_failstring(HsPtr);
extern void* prim_setBkMode(HDC arg1,UINT arg2);
extern UINT access_prim_setBkMode_res1(HsPtr);
extern int access_prim_setBkMode_gc_failed(HsPtr);
extern void* access_prim_setBkMode_gc_failstring(HsPtr);
extern void* prim_getBkMode(HDC arg1);
extern UINT access_prim_getBkMode_res1(HsPtr);
extern int access_prim_getBkMode_gc_failed(HsPtr);
extern void* access_prim_getBkMode_gc_failstring(HsPtr);
extern void* prim_setBrushOrgEx(HDC arg1,int arg2,int arg3);
extern LONG access_prim_setBrushOrgEx_gc_res1(HsPtr);
extern LONG access_prim_setBrushOrgEx_gc_res2(HsPtr);
extern int access_prim_setBrushOrgEx_gc_failed(HsPtr);
extern void* access_prim_setBrushOrgEx_gc_failstring(HsPtr);
extern void* prim_getBrushOrgEx(HDC arg1);
extern LONG access_prim_getBrushOrgEx_gc_res1(HsPtr);
extern LONG access_prim_getBrushOrgEx_gc_res2(HsPtr);
extern int access_prim_getBrushOrgEx_gc_failed(HsPtr);
extern void* access_prim_getBrushOrgEx_gc_failstring(HsPtr);
extern void* prim_setTextAlign(HDC arg1,UINT arg2);
extern UINT access_prim_setTextAlign_res1(HsPtr);
extern int access_prim_setTextAlign_gc_failed(HsPtr);
extern void* access_prim_setTextAlign_gc_failstring(HsPtr);
extern void* prim_getTextAlign(HDC arg1);
extern UINT access_prim_getTextAlign_res1(HsPtr);
extern int access_prim_getTextAlign_gc_failed(HsPtr);
extern void* access_prim_getTextAlign_gc_failstring(HsPtr);
extern void* prim_setTextCharacterExtra(HDC arg1,int arg2);
extern int access_prim_setTextCharacterExtra_res1(HsPtr);
extern int access_prim_setTextCharacterExtra_gc_failed(HsPtr);
extern void* access_prim_setTextCharacterExtra_gc_failstring(HsPtr);
extern void* prim_getTextCharacterExtra(HDC arg1);
extern int access_prim_getTextCharacterExtra_res1(HsPtr);
extern int access_prim_getTextCharacterExtra_gc_failed(HsPtr);
extern void* access_prim_getTextCharacterExtra_gc_failstring(HsPtr);
extern void* prim_getMiterLimit(HDC arg1);
extern float access_prim_getMiterLimit_res1(HsPtr);
extern int access_prim_getMiterLimit_gc_failed(HsPtr);
extern void* access_prim_getMiterLimit_gc_failstring(HsPtr);
extern void* prim_setMiterLimit(HDC arg1,float arg2);
extern float access_prim_setMiterLimit_res1(HsPtr);
extern int access_prim_setMiterLimit_gc_failed(HsPtr);
extern void* access_prim_setMiterLimit_gc_failstring(HsPtr);
extern void* prim_saveDC(HDC arg1);
extern int access_prim_saveDC_res1(HsPtr);
extern int access_prim_saveDC_gc_failed(HsPtr);
extern void* access_prim_saveDC_gc_failstring(HsPtr);
extern void* prim_restoreDC(HDC arg1,int arg2);
extern int access_prim_restoreDC_gc_failed(HsPtr);
extern void* access_prim_restoreDC_gc_failstring(HsPtr);
extern void* prim_getCurrentBitmap(HDC arg1);
extern HBITMAP access_prim_getCurrentBitmap_res1(HsPtr);
extern int access_prim_getCurrentBitmap_gc_failed(HsPtr);
extern void* access_prim_getCurrentBitmap_gc_failstring(HsPtr);
extern void* prim_getCurrentBrush(HDC arg1);
extern HBRUSH access_prim_getCurrentBrush_res1(HsPtr);
extern int access_prim_getCurrentBrush_gc_failed(HsPtr);
extern void* access_prim_getCurrentBrush_gc_failstring(HsPtr);
extern void* prim_getCurrentFont(HDC arg1);
extern HFONT access_prim_getCurrentFont_res1(HsPtr);
extern int access_prim_getCurrentFont_gc_failed(HsPtr);
extern void* access_prim_getCurrentFont_gc_failstring(HsPtr);
extern void* prim_getCurrentPalette(HDC arg1);
extern HPALETTE access_prim_getCurrentPalette_res1(HsPtr);
extern int access_prim_getCurrentPalette_gc_failed(HsPtr);
extern void* access_prim_getCurrentPalette_gc_failstring(HsPtr);
extern void* prim_getCurrentPen(HDC arg1);
extern HPEN access_prim_getCurrentPen_res1(HsPtr);
extern int access_prim_getCurrentPen_gc_failed(HsPtr);
extern void* access_prim_getCurrentPen_gc_failstring(HsPtr);
extern void* prim_selectBitmap(HDC arg1,HBITMAP arg2);
extern HBITMAP access_prim_selectBitmap_res1(HsPtr);
extern int access_prim_selectBitmap_gc_failed(HsPtr);
extern void* access_prim_selectBitmap_gc_failstring(HsPtr);
extern void* prim_selectBrush(HDC arg1,HBRUSH arg2);
extern HBRUSH access_prim_selectBrush_res1(HsPtr);
extern int access_prim_selectBrush_gc_failed(HsPtr);
extern void* access_prim_selectBrush_gc_failstring(HsPtr);
extern void* prim_selectFont(HDC arg1,HFONT arg2);
extern HFONT access_prim_selectFont_res1(HsPtr);
extern int access_prim_selectFont_gc_failed(HsPtr);
extern void* access_prim_selectFont_gc_failstring(HsPtr);
extern void* prim_selectPen(HDC arg1,HPEN arg2);
extern HPEN access_prim_selectPen_res1(HsPtr);
extern int access_prim_selectPen_gc_failed(HsPtr);
extern void* access_prim_selectPen_gc_failstring(HsPtr);
extern void* prim_selectPalette(HDC arg1,HPALETTE arg2,int arg3);
extern HPALETTE access_prim_selectPalette_res1(HsPtr);
extern int access_prim_selectPalette_gc_failed(HsPtr);
extern void* access_prim_selectPalette_gc_failstring(HsPtr);
extern void* prim_selectRgn(HDC arg1,HRGN arg2);
extern WORD access_prim_selectRgn_res1(HsPtr);
extern int access_prim_selectRgn_gc_failed(HsPtr);
extern void* access_prim_selectRgn_gc_failstring(HsPtr);
extern void* prim_selectClipRgn(HDC arg1,HRGN arg2);
extern WORD access_prim_selectClipRgn_res1(HsPtr);
extern int access_prim_selectClipRgn_gc_failed(HsPtr);
extern void* access_prim_selectClipRgn_gc_failstring(HsPtr);
extern void* prim_extSelectClipRgn(HDC arg1,HRGN arg2,UINT arg3);
extern WORD access_prim_extSelectClipRgn_res1(HsPtr);
extern int access_prim_extSelectClipRgn_gc_failed(HsPtr);
extern void* access_prim_extSelectClipRgn_gc_failstring(HsPtr);
extern void* prim_selectClipPath(HDC arg1,UINT arg2);
extern WORD access_prim_selectClipPath_res1(HsPtr);
extern int access_prim_selectClipPath_gc_failed(HsPtr);
extern void* access_prim_selectClipPath_gc_failstring(HsPtr);
extern void* prim_cancelDC(HDC arg1);
extern int access_prim_cancelDC_gc_failed(HsPtr);
extern void* access_prim_cancelDC_gc_failstring(HsPtr);
extern void* prim_createCompatibleDC(HDC arg1);
extern HDC access_prim_createCompatibleDC_res1(HsPtr);
extern int access_prim_createCompatibleDC_gc_failed(HsPtr);
extern void* access_prim_createCompatibleDC_gc_failstring(HsPtr);
extern void* prim_deleteDC(HDC arg1);
extern int access_prim_deleteDC_gc_failed(HsPtr);
extern void* access_prim_deleteDC_gc_failstring(HsPtr);
