#include <windows.h>
#include "errors.h"
#include "win32debug.h"
#include "diatemp.h"
#include "HsFFI.h"
extern void * prim_mkResource(int arg1);
extern void* prim_dialogBox(HINSTANCE hInst,LPCTSTR lpTemp,HWND hWndParent,void * diaFun);
extern int access_prim_dialogBox_res1(HsPtr);
extern int access_prim_dialogBox_gc_failed(HsPtr);
extern void* access_prim_dialogBox_gc_failstring(HsPtr);
extern void* prim_dialogBoxParam(HINSTANCE hInst,LPCTSTR lpTemp,HWND hWndParent,void * diaFun,LPARAM dwInit);
extern int access_prim_dialogBoxParam_res1(HsPtr);
extern int access_prim_dialogBoxParam_gc_failed(HsPtr);
extern void* access_prim_dialogBoxParam_gc_failstring(HsPtr);
extern void* prim_dialogBoxIndirect(HINSTANCE hInst,void * lpTemp,HWND hWndParent,void * diaFun);
extern int access_prim_dialogBoxIndirect_res1(HsPtr);
extern int access_prim_dialogBoxIndirect_gc_failed(HsPtr);
extern void* access_prim_dialogBoxIndirect_gc_failstring(HsPtr);
extern void* prim_dialogBoxIndirectParam(HINSTANCE hInst,void * lpTemp,HWND hWndParent,void * diaFun,LPARAM dwInit);
extern int access_prim_dialogBoxIndirectParam_res1(HsPtr);
extern int access_prim_dialogBoxIndirectParam_gc_failed(HsPtr);
extern void* access_prim_dialogBoxIndirectParam_gc_failstring(HsPtr);
extern void * prim_getFinalDialog(void * arg1);
extern void * prim_mkDiaTemplate(int arg1,int arg2,int arg3,int arg4,int arg5,DWORD arg6,DWORD arg7,void * arg8,void * arg9,void * arg10,void * arg11,int arg12);
extern void * prim_addDiaControl(void * arg1,void * arg2,int arg3,void * arg4,DWORD arg5,int arg6,int arg7,int arg8,int arg9,DWORD arg10);
extern void * prim_toUnicodeStr(char * arg1);
extern void* prim_createDialog(HINSTANCE hInst,LPCTSTR lpTemp,HWND hWndParent,void * diaFun);
extern HWND access_prim_createDialog_res1(HsPtr);
extern int access_prim_createDialog_gc_failed(HsPtr);
extern void* access_prim_createDialog_gc_failstring(HsPtr);
extern void* prim_createDialogParam(HINSTANCE hInst,LPCTSTR lpTemp,HWND hWndParent,void * diaFun,LPARAM dwInit);
extern HWND access_prim_createDialogParam_res1(HsPtr);
extern int access_prim_createDialogParam_gc_failed(HsPtr);
extern void* access_prim_createDialogParam_gc_failstring(HsPtr);
extern void* prim_createDialogIndirect(HINSTANCE hInst,void * lpTemp,HWND hWndParent,void * diaFun);
extern HWND access_prim_createDialogIndirect_res1(HsPtr);
extern int access_prim_createDialogIndirect_gc_failed(HsPtr);
extern void* access_prim_createDialogIndirect_gc_failstring(HsPtr);
extern void* prim_createDialogIndirectParam(HINSTANCE hInst,void * lpTemp,HWND hWndParent,void * diaFun,LPARAM dwInit);
extern HWND access_prim_createDialogIndirectParam_res1(HsPtr);
extern int access_prim_createDialogIndirectParam_gc_failed(HsPtr);
extern void* access_prim_createDialogIndirectParam_gc_failstring(HsPtr);
extern LRESULT prim_defDlgProc(HWND arg1,DWORD arg2,WPARAM arg3,LPARAM arg4);
extern void* prim_endDialog(HWND arg1,int arg2);
extern BOOL access_prim_endDialog_res1(HsPtr);
extern int access_prim_endDialog_gc_failed(HsPtr);
extern void* access_prim_endDialog_gc_failstring(HsPtr);
extern LONG prim_getDialogBaseUnits();
extern void* prim_getDlgCtrlID(HWND arg1);
extern int access_prim_getDlgCtrlID_res1(HsPtr);
extern int access_prim_getDlgCtrlID_gc_failed(HsPtr);
extern void* access_prim_getDlgCtrlID_gc_failstring(HsPtr);
extern void* prim_getDlgItem(HWND arg1,int arg2);
extern HWND access_prim_getDlgItem_res1(HsPtr);
extern int access_prim_getDlgItem_gc_failed(HsPtr);
extern void* access_prim_getDlgItem_gc_failstring(HsPtr);
extern void* prim_getDlgItemInt(HWND arg1,int arg2,int arg3);
extern int access_prim_getDlgItemInt_res1(HsPtr);
extern int access_prim_getDlgItemInt_gc_failed(HsPtr);
extern void* access_prim_getDlgItemInt_gc_failstring(HsPtr);
extern void* prim_getDlgItemText(HWND arg1,int arg2,int arg3);
extern char * access_prim_getDlgItemText_gc_res2(HsPtr);
extern int access_prim_getDlgItemText_gc_failed(HsPtr);
extern void* access_prim_getDlgItemText_gc_failstring(HsPtr);
extern void* prim_getNextDlgGroupItem(HWND arg1,HWND arg2,BOOL arg3);
extern HWND access_prim_getNextDlgGroupItem_res1(HsPtr);
extern int access_prim_getNextDlgGroupItem_gc_failed(HsPtr);
extern void* access_prim_getNextDlgGroupItem_gc_failstring(HsPtr);
extern void* prim_getNextDlgTabItem(HWND arg1,HWND arg2,BOOL arg3);
extern HWND access_prim_getNextDlgTabItem_res1(HsPtr);
extern int access_prim_getNextDlgTabItem_gc_failed(HsPtr);
extern void* access_prim_getNextDlgTabItem_gc_failstring(HsPtr);
extern BOOL prim_isDialogMessage(HWND arg1,MSG * arg2);
extern void* prim_mapDialogRect(HWND arg1,LPRECT arg2);
extern int access_prim_mapDialogRect_gc_failed(HsPtr);
extern void* access_prim_mapDialogRect_gc_failstring(HsPtr);
extern LONG prim_sendDlgItemMessage(HWND arg1,int arg2,DWORD arg3,WPARAM arg4,LPARAM arg5);
extern void* prim_setDlgItemInt(HWND arg1,int arg2,UINT arg3,BOOL arg4);
extern int access_prim_setDlgItemInt_gc_failed(HsPtr);
extern void* access_prim_setDlgItemInt_gc_failstring(HsPtr);
extern void* prim_setDlgItemText(HWND arg1,int arg2,char * arg3);
extern int access_prim_setDlgItemText_gc_failed(HsPtr);
extern void* access_prim_setDlgItemText_gc_failstring(HsPtr);
extern DWORD prim_dS_3DLOOK();
extern DWORD prim_dS_ABSALIGN();
extern DWORD prim_dS_CENTER();
extern DWORD prim_dS_CENTERMOUSE();
extern DWORD prim_dS_CONTEXTHELP();
extern DWORD prim_dS_CONTROL();
extern DWORD prim_dS_FIXEDSYS();
extern DWORD prim_dS_LOCALEDIT();
extern DWORD prim_dS_MODALFRAME();
extern DWORD prim_dS_NOFAILCREATE();
extern DWORD prim_dS_NOIDLEMSG();
extern DWORD prim_dS_SETFONT();
extern DWORD prim_dS_SETFOREGROUND();
extern DWORD prim_dS_SYSMODAL();
extern DWORD prim_dM_GETDEFID();
extern DWORD prim_dM_REPOSITION();
extern DWORD prim_dM_SETDEFID();
extern DWORD prim_wM_CTLCOLORDLG();
extern DWORD prim_wM_CTLCOLORMSGBOX();
